FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY Gateway ./Gateway
COPY pom.xml .

RUN mvn -f Gateway/pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=build /app/Gateway/target/*.jar gateway.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "gateway.jar"]