---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: broker
      nodePort: 30092
      port: 9092
      targetPort: 9092
    - name: controller
      nodePort: 30093
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
  type: NodePort